--- 
abstract: Load configuration from different file formats, transparently
author: Joel Bernstein  <rataxis@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Config-Any
no_index: 
  directory: 
    - inc
    - t
requires: 
  Module::Pluggable: 3.01
  Test::More: 0
  version: 0
version: 0.08
