---
abstract: 'Load configuration from different file formats, transparently'
author:
  - 'Joel Bernstein <rataxis@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Any
no_index:
  directory:
    - inc
    - t
requires:
  Module::Pluggable: 3.01
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
